/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ResumeAnalysis = IDL.Record({
  'suggestions' : IDL.Vec(IDL.Text),
  'overallScore' : IDL.Nat,
  'strengths' : IDL.Vec(IDL.Text),
  'wordCount' : IDL.Nat,
  'experienceYears' : IDL.Nat,
  'skills' : IDL.Vec(IDL.Text),
  'educationLevel' : IDL.Text,
});

export const idlService = IDL.Service({
  'analyzeResume' : IDL.Func([IDL.Text, IDL.Text], [ResumeAnalysis], []),
  'getRecentAnalyses' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ResumeAnalysis)],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ResumeAnalysis = IDL.Record({
    'suggestions' : IDL.Vec(IDL.Text),
    'overallScore' : IDL.Nat,
    'strengths' : IDL.Vec(IDL.Text),
    'wordCount' : IDL.Nat,
    'experienceYears' : IDL.Nat,
    'skills' : IDL.Vec(IDL.Text),
    'educationLevel' : IDL.Text,
  });
  
  return IDL.Service({
    'analyzeResume' : IDL.Func([IDL.Text, IDL.Text], [ResumeAnalysis], []),
    'getRecentAnalyses' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ResumeAnalysis)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };